version: '4.4'

services:
  mysql:
    image: mysql:8.0
    container_name: go_gin_crud_mysql
    ports:
      - "3307:3306"   # MySQL (host 3307 -> container 3306)
    environment:
      MYSQL_ROOT_PASSWORD: a3935522
      MYSQL_DATABASE: goGinCRUD
      MYSQL_USER: gogin
      MYSQL_PASSWORD: a3935522
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - go-gin-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:

networks:
  go-gin-network:
    driver: bridge

